import { Header, VendorList } from "@components/index";
import { Vendor } from "@components/vendor-list";
import { Page } from "@geist-ui/core";
import { vendors } from "@lib/vendors";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Smooder App - Home Page</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <Page.Header>
          <Header />
        </Page.Header>
        <Page.Content>
          <VendorList vendors={vendors} />
        </Page.Content>
      </Page>
    </div>
  );
};

export default Home;
